line-length = 120
target-version = 'py310'

[format]
quote-style = 'single'

[lint]
select = ['ALL']
ignore = [
  'D100',
  'D107',
  'D200',
  'D202',
  'D212',
  'COM812',
  'ANN401',
  'TRY003',
  'EM101',
  'EM102',
  'D103',
  'D102',
  'D101',
]

[lint.flake8-quotes]
inline-quotes = 'single'

[lint.isort]
lines-after-imports = 2
